// src/modules/auth/domain/events/auditoria-event.types.js

export const AUDIT_EVENT_TYPES = Object.freeze({
  LOGIN_SUCCESS: 'AUTH.LOGIN_SUCCESS',

  LOGIN_FAILED: 'AUTH.LOGIN_FAILED',

  LOGOUT: 'AUTH.LOGOUT',

  LOGOUT_ALL: 'AUTH.LOGOUT_ALL',

  TOKEN_REFRESH: 'AUTH.TOKEN_REFRESH',

  SESSION_REVOKED: 'AUTH.SESSION_REVOKED',

  PASSWORD_CHANGED: 'AUTH.PASSWORD_CHANGED',

  PASSWORD_RESET: 'AUTH.PASSWORD_RESET',

  ACCOUNT_LOCKED: 'AUTH.ACCOUNT_LOCKED',

  ACCOUNT_UNLOCKED: 'AUTH.ACCOUNT_UNLOCKED',

  PERMISSION_DENIED: 'AUTH.PERMISSION_DENIED',

  ROLE_CHANGED: 'AUTH.ROLE_CHANGED',

  USER_CREATED: 'AUTH.USER_CREATED',

  USER_UPDATED: 'AUTH.USER_UPDATED',
});
