export const ERROR_CODES = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  VALIDATION_ERROR: 'VALIDATION_ERROR',

  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',

  UNAUTHORIZED: 'UNAUTHORIZED',

  FORBIDDEN: 'FORBIDDEN',

  NOT_FOUND: 'NOT_FOUND',

  CONFLICT: 'CONFLICT',

  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
};
