export const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',

  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',

  UNAUTHORIZED: 'UNAUTHORIZED',

  FORBIDDEN: 'FORBIDDEN',

  DOMAIN_ERROR: 'DOMAIN_ERROR',

  INFRASTRUCTURE_ERROR: 'INFRASTRUCTURE_ERROR',

  INTERNAL_ERROR: 'INTERNAL_ERROR',
});
